module.exports = {
    CREATE_CALENDAR: 'CREATE_CALENDAR',
    DELETE_CALENDAR: 'DELETE_CALENDAR',
    GET_CALENDARS: 'GET_CALENDARS',
    UPDATE_CALENDAR: 'UPDATE_CALENDAR',
    SHARE_CALENDAR: 'SHARE_CALENDAR',

    CREATE_EVENT: 'CREATE_EVENT',
    UPDATE_EVENT: 'UPDATE_EVENT',
    DELETE_EVENT: 'DELETE_EVENT',
    SHARE_EVENT: 'SHARE_EVENT'
};