module.exports = {
    CALENDAR_CREATED: 'CALENDAR_CREATED',
    CALENDAR_DELETED: 'CALENDAR_DELETED',
    CALENDARS: 'CALENDARS',
    CALENDAR_UPDATED: 'CALENDAR_UPDATED',
    CALENDAR_SHARED: 'CALENDAR_SHARED',

    EVENT_CREATED: 'EVENT_CREATED',
    EVENT_UPDATED: 'EVENT_UPDATED',
    EVENT_DELETED: 'EVENT_DELETED',
    EVENT_SHARED: 'EVENT_SHARED'
};